name: Code CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/code_ci.yml'
      - '!**/linux_ci.yml'
      - '!**/macos_ci.yml'
      - '!**/windows_ci.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/code_ci.yml'
      - '!**/linux_ci.yml'
      - '!**/macos_ci.yml'
      - '!**/windows_ci.yml'

concurrency:
  group: code-ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  linux-tcc:
    uses: ./.github/workflows/linux_tcc_ci.yml

  linux-gcc:
    uses: ./.github/workflows/linux_gcc_ci.yml

  linux-clang:
    uses: ./.github/workflows/linux_clang_ci.yml

  macos:
    uses: ./.github/workflows/macos_ci.yml

  windows:
    uses: ./.github/workflows/windows_ci.yml
