name: Docker Ubuntu MUSL CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/docker_ubuntu.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/docker_ubuntu.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'master' && github.sha || github.ref_name }}
  cancel-in-progress: true

jobs:
  ubuntu-docker-musl:
    runs-on: ubuntu-20.04
    timeout-minutes: 121
    container:
      image: thevlang/vlang:ubuntu-build
      env:
        V_CI_MUSL: 1
        V_CI_UBUNTU_MUSL: 1
        VFLAGS: -cc musl-gcc -gc none
      volumes:
        - ${{ github.workspace }}:/opt/vlang

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build V
        run: echo $VFLAGS && make -j4 && ./v -cg -o v cmd/v
      - name: Verify `v test` works
        run: |
          ./v cmd/tools/test_if_v_test_system_works.v
          ./cmd/tools/test_if_v_test_system_works

      - name: Verify formatting
        run: ./v test-cleancode

      - name: Test V fixed tests
        run: ./v test-self
