name: CI Linux (TCC)

on:
  workflow_call:

env:
  VFLAGS: -cc tcc -no-retry-compilation
  CACHE_ID: linux-tcc-${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    steps:
      - uses: actions/checkout@v4
      - name: Setup dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libssl-dev sqlite3 libsqlite3-dev valgrind libfreetype6-dev libxi-dev libxcursor-dev libgl-dev expect
          version: 1.0
      - name: Build V
        run: |
          echo $VFLAGS
          make -j4
          thirdparty/tcc/tcc.exe -version
          ./v -showcc -cg -cstrict -o v cmd/v # Make sure vtcc can build itself twice
      - name: Cache
        uses: actions/cache/save@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}

  # TODO: test binaries separately
  verify:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}
          fail-on-cache-miss: true
      - name: Print System and Environment Info
        run: ./v doctor
      - name: Self compile
        run: |
          ./v -d debug_malloc -d debug_realloc -o v cmd/v
          ./v -o v2 cmd/v && ./v2 -o v3 cmd/v && ./v3 -o v4 cmd/v
          # Test v -realloc arena allocation
          ./v -o vrealloc -prealloc cmd/v && ./vrealloc -o v3 cmd/v && ./v3 -o v4 cmd/v
          # Test self compilation with -skip-unused
          ./v -skip-unused -o v2 cmd/v && ./v2 -skip-unused -o v3 cmd/v && ./v3 -skip-unused -o v4 cmd/v
      - name: Verify `v test` works
        run: |
          ./v cmd/tools/test_if_v_test_system_works.v
          ./cmd/tools/test_if_v_test_system_works
      - name: Test pure V math module
        run: ./v -exclude @vlib/math/*.c.v test vlib/math/

  fmt:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}
          fail-on-cache-miss: true
      - name: Test fmt
        run: ./v test-fmt
      - name: Test cleancode
        run: ./v test-cleancode

  test-self:
    needs: verify
    runs-on: ubuntu-20.04
    timeout-minutes: 90
    strategy:
      matrix:
        optimization: ['', '-prod', '-cstrict']
        include:
          - optimization: '-cstrict'
            env: 'VTEST_JUST_ESSENTIAL=1 V_CI_CSTRICT=1'
      fail-fast: false
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}
          fail-on-cache-miss: true
      - name: Setup dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libssl-dev sqlite3 libsqlite3-dev valgrind libfreetype6-dev libxi-dev libxcursor-dev libgl-dev expect
          version: 1.0
      - name: Self test
        run: ./v test-self
      - name: Self tests (-cstrict)
        run: VTEST_JUST_ESSENTIAL=1 V_CI_CSTRICT=1 ./v -cstrict test-self

  test-other:
    needs: verify
    runs-on: ubuntu-20.04
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}
          fail-on-cache-miss: true
      - name: Build V binaries
        run: ./v build-vbinaries
      - name: Build benches
        run: ./v should-compile-all vlib/v/tests/bench/
      - name: Build option_test.v with -autofree
        run: ./v -autofree vlib/v/tests/option_test.v
      - name: Test password input
        run: ./v test examples/password/
      - name: Test readline
        run: ./v test examples/readline/

  c2v:
    needs: verify
    uses: ./.github/workflows/c2v_ci.yml
    with:
      os: ubuntu-20.04
      cc: tcc
      vflags: -cc tcc -no-retry-compilation

  # TODO: use re-usable workflow
  build-modules:
    needs: verify
    runs-on: ubuntu-20.04
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}
          fail-on-cache-miss: true
      - name: Setup dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: libssl-dev sqlite3 libsqlite3-dev valgrind libfreetype6-dev libxi-dev libxcursor-dev libgl-dev expect
          version: 1.0
      - name: Setup example dependencies
        run: |
          sudo apt install --quiet -y xfonts-75dpi xfonts-base
          # The following is needed for examples/wkhtmltopdf.v
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
          sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
      - name: Build examples
        run: ./v -W build-examples
      - name: Build V tools
        run: ./v -W build-tools
      - name: Test V tutorials
        run: ./v tutorials/building_a_simple_web_blog_with_vweb/code/blog
      - name: Build cmd/tools/fast
        run: cd cmd/tools/fast && ../../../v fast.v && ./fast
      - name: Build with -usecache
        run: |
          unset VFLAGS
          ./v -usecache examples/hello_world.v && examples/hello_world
          ./v -o v2 -usecache cmd/v
          ./v2 -o v3 -usecache cmd/v
          ./v3 version
          ./v3 -o tetris -usecache examples/tetris/tetris.v
      - name: Test password input
        run: ./v test examples/password/
      - name: Test readline
        run: ./v test examples/readline/
