name: CI Linux (TCC Boehm GC)

on:
  workflow_call:

env:
  VFLAGS: -cc tcc -no-retry-compilation

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install --quiet -y libssl-dev sqlite3 libsqlite3-dev valgrind
          sudo apt-get install --quiet -y libfreetype6-dev  libxi-dev libxcursor-dev libgl-dev
          sudo apt-get install --quiet -y libgc-dev
          # The following is needed for examples/wkhtmltopdf.v
          wget https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6-1/wkhtmltox_0.12.6-1.focal_amd64.deb
          sudo apt-get install --quiet -y xfonts-75dpi xfonts-base
          sudo dpkg -i wkhtmltox_0.12.6-1.focal_amd64.deb
      - name: Build v
        run: |
          make -j4
          thirdparty/tcc/tcc.exe -version
          ./v -showcc -cg -o v cmd/v # Make sure vtcc can build itself twice
      - name: v self compilation with -gc boehm
        run: |
          ./v -gc boehm -o v2 cmd/v && ./v2 -gc boehm -o v3 cmd/v && ./v3 -gc boehm -o v4 cmd/v
          mv v4 v
      - name: v doctor
        run: |
          ./v doctor
      - name: Verify `v -gc boehm test` works
        run: |
          ./v -gc boehm cmd/tools/test_if_v_test_system_works.v
          ./cmd/tools/test_if_v_test_system_works
      - name: All code is formatted
        run: ./v test-cleancode
      - name: Self tests with `-gc boehm` with V compiler using Boehm-GC itself
        run: ./v -gc boehm test-self
      - name: Test leak detector
        run: |
          ./v -gc boehm_leak -o testcase_leak vlib/v/tests/testcase_leak.vv
          ./testcase_leak 2>leaks.txt
          grep "Found 1 leaked object" leaks.txt && grep -P ", sz=\s?1000," leaks.txt
      - name: Test leak detector not being active for `-gc boehm`
        run: |
          ./v -gc boehm -o testcase_leak vlib/v/tests/testcase_leak.vv
          ./testcase_leak 2>leaks.txt
          [ "$(stat -c %s leaks.txt)" = "0" ]
      - name: Test leak detector not being active for normal compile
        run: |
          ./v -o testcase_leak vlib/v/tests/testcase_leak.vv
          ./testcase_leak 2>leaks.txt
          [ "$(stat -c %s leaks.txt)" = "0" ]
