name: vlib modules CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-module-docs:
    runs-on: ubuntu-20.04
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: make
      - name: Build module documentation
        run: ./v doc -m -f html vlib/
      - name: Deploy docs to vercel
        if: github.event.repository.full_name == 'vlang/v'
        run: npx vercel --confirm --prod --name vmodules --token ${{ secrets.VERCEL_TOKEN }} vlib/_docs/ || true
