name: vlib modules CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build-module-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4	
      - name: Build V
        run: make -j4
      - name: Build module documentation
        run: ./v doc -m -f html vlib/
      - name: Deploy docs to vercel
        if: ${{ github.event_name == 'push' && github.event.repository.full_name == 'vlang/v' && github.event.ref == 'refs/heads/master' }}
        run: npx vercel --confirm --prod --name vmodules --token ${{ secrets.VERCEL_TOKEN }} vlib/_docs/ || true
