name: Other CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/other_ci.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/other_ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'master' && github.sha || github.ref_name }}
  cancel-in-progress: true

jobs:
  no-gpl-by-accident:
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: No GPL licensed code, should be added accidentally
        run: |
          ! grep -r --exclude="*.yml" "a GPL license" .

  code-formatting:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      VFLAGS: -cc gcc
    steps:
      - uses: actions/checkout@v4
      - name: Environment info
        run: echo $VFLAGS $GITHUB_SHA $GITHUB_REF
      - name: Build local v
        run: make -j4
      - name: v test-cleancode
        run: ./v test-cleancode
      - name: v test-fmt
        run: ./v test-fmt

  performance-regressions:
    runs-on: ubuntu-20.04
    timeout-minutes: 30
    env:
      VFLAGS: -cc gcc
    steps:
      - uses: actions/checkout@v4
      - name: Environment info
        run: echo $VFLAGS $GITHUB_SHA $GITHUB_REF
      - name: Build local v
        run: make -j4
      - name: Clone & Build previous vmaster/v
        run: |
          v retry -- git clone --depth=1 https://github.com/vlang/v vmaster/
          (cd vmaster; make -j4)
      - name: V versions
        run: ./v version && ./vmaster/v version
      - name: Build the repeat tool
        run: ./v cmd/tools/vrepeat.v
      - name: Repeat -o hw.c examples/hello_world.v
        run: ./v repeat --max_time 251 --series 3 --runs 20 --nmins 2 --nmaxs 5 --warmup 3 --fail_percent 10 -t 'cd {T} ; ./v -o hw.c examples/hello_world.v' . ./vmaster
      - name: Repeat -o v.c cmd/v
        run: ./v repeat --max_time 1731 --series 3 --runs 20 --nmins 2 --nmaxs 5 --warmup 3 --fail_percent 10 -t 'cd {T} ; ./v -o v.c cmd/v' . ./vmaster

  misc-tooling:
    runs-on: ubuntu-20.04
    timeout-minutes: 121
    env:
      VFLAGS: -cc tcc -no-retry-compilation
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - name: Build V
        run: make -j4
      - name: Install dependencies
        run: |
          ./v retry -- sudo apt -qq update
          ./v retry -- sudo apt -qq install libsodium-dev libssl-dev sqlite3 libsqlite3-dev postgresql libpq-dev valgrind
          ./v retry -- sudo apt -qq install libfreetype6-dev libxi-dev libxcursor-dev libgl-dev xfonts-75dpi xfonts-base
          ./v retry -- sudo apt -qq install g++-9 g++-11
      - name: g++-9 version
        run: g++-9 --version
      - name: V self compilation with g++ and -std=c++11
        run: ./v -cc g++-9 -no-std -cflags -std=c++11 -o v2 cmd/v && ./v2 -cc g++-9 -no-std -cflags -std=c++11 -o v3 cmd/v
      - name: g++-11 version
        run: g++-11 --version
      - name: V self compilation with g++ and -std=c++20
        run: ./v -cc g++-11 -no-std -cflags -std=c++20 -o v2 cmd/v && ./v2 -cc g++-11 -no-std -cflags -std=c++20 -o v3 cmd/v
        # NB: this does not mean it runs, but at least keeps it from regressing
      - name: Ensure V can be compiled with -autofree
        run: ./v -autofree -o v2 cmd/v
      - name: Shader examples can be built
        run: |
          .github/workflows/compile_shaders_in_examples.sh
          ./v should-compile-all examples/sokol/*.v examples/sokol/0?*/*.v

  parser-silent:
    runs-on: ubuntu-20.04
    timeout-minutes: 121
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: make -j4
      - name: Install zzuf
        run: ./v retry sudo apt -qq install zzuf
      - name: Run test-parser
        run: |
          ./v -g -d trace_parse_stmt cmd/tools/vtest-parser.v
          examples=(hello_world.v hanoi.v fibonacci.v cli.v json.v vmod.v regex/regex_example.v 2048/2048.v)
          for m in "${examples[@]}"; do
            ./v test-parser --show_source --linear examples/$m
          done
      - name: Run test-parser over fuzzed files
        run: |
          examples=(hello_world hanoi fibonacci cli json vmod regex/regex_example 2048/2048)
          for m in "${examples[@]}"; do
            zzuf -R '\x00-\x20\x7f-\xff' -r0.01 < examples/$m.v > examples/$m_fuzz.v
          done
          for m in "${examples[@]}"; do
            ./v test-parser --show_source --linear examples/$m_fuzz.v
          done
