name: Time CI

# on:
#   push:
#     paths-ignore:
#       - '**.md'
#       - '**.yml'
#       - '!**/time_ci.yml'
#   pull_request:
#     paths-ignore:
#       - '**.md'
#       - '**.yml'
#       - '!**/time_ci.yml'

concurrency:
  group: time-ci-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  test-nix:
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-12]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: make -j4
      - name: Test time functions in a timezone UTC-12
        run: TZ=Etc/GMT+12 ./v test vlib/time/
      - name: Test time functions in a timezone UTC-3
        run: TZ=Etc/GMT+3 ./v test vlib/time/
      - name: Test time functions in a timezone UTC+3
        run: TZ=Etc/GMT-3 ./v test vlib/time/
      - name: Test time functions in a timezone UTC+12
        run: TZ=Etc/GMT-12 ./v test vlib/time/
      - name: Test time functions in a timezone using daylight saving (Europe/Paris)
        run: TZ=Europe/Paris ./v test vlib/time/

  test-windows:
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: .\make.bat
      - name: Test time functions in a timezone UTC-12
        run: tzutil /s "Dateline Standard Time" && ./v test vlib/time/
      - name: Test time functions in a timezone UTC-3
        run: tzutil /s "Greenland Standard Time" && ./v test vlib/time/
      - name: Test time functions in a timezone UTC+3
        run: tzutil /s "Russian Standard Time" && ./v test vlib/time/
      - name: Test time functions in a timezone UTC+12
        run: tzutil /s "New Zealand Standard Time" && ./v test vlib/time/
      - name: Test time functions in a timezone using daylight saving (Europe/Paris)
        run: tzutil /s "W. Europe Standard Time" && ./v test vlib/time/
