name: Time CI

on:
  workflow_call:
    inputs:
      cache_id:
        description: 'The ID to the V cache passed from the caller workflow'
        required: true
        type: string
      os:
        required: true
        type: string

jobs:
  test-nix:
    runs-on: ${{ inputs.os }}
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ inputs.cache_id }}
          fail-on-cache-miss: true
      - name: Test time functions in a timezone UTC-12
        run: TZ=Etc/GMT+12 ./v test vlib/time/
      - name: Test time functions in a timezone UTC-3
        run: TZ=Etc/GMT+3 ./v test vlib/time/
      - name: Test time functions in a timezone UTC+3
        run: TZ=Etc/GMT-3 ./v test vlib/time/
      - name: Test time functions in a timezone UTC+12
        run: TZ=Etc/GMT-12 ./v test vlib/time/
      - name: Test time functions in a timezone using daylight saving (Europe/Paris)
        run: TZ=Europe/Paris ./v test vlib/time/
