name: toml CI

on:
  push:
    paths-ignore:
      - "**.md"
      - '**.yml'
      - '!**/toml_ci.yml'
  pull_request:
    paths-ignore:
      - "**.md"
      - '**.yml'
      - '!**/toml_ci.yml'

env:
  RETRY: .github/workflows/retry.sh

jobs:
  toml-module-pass-external-test-suites:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          $RETRY sudo apt-get update
          $RETRY sudo apt-get install --quiet -y jq libgc-dev
      - name: Build V
        run: make

      - name: Show JQ Version
        run: jq --version

      - name: Download more TOML testsuits
        run: .github/workflows/download_full_toml_test_suites.sh

      - name: Run TOML tests
        run: VTEST_TOML_DO_YAML_CONVERSION=1 VTEST_TOML_DO_LARGE_FILES=1 ./v test vlib/toml
