name: toml CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/toml_ci.yml'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.yml'
      - '!**/toml_ci.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref == 'refs/heads/master' && github.sha || github.ref }}
  cancel-in-progress: true

jobs:
  toml-module-pass-external-test-suites:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          .github/workflows/retry.sh sudo apt -qq update
          .github/workflows/retry.sh sudo apt -qq install jq libgc-dev

      - name: Build V
        run: make -j4

      - name: Show JQ Version
        run: jq --version

      - name: Download more TOML testsuits
        run: .github/workflows/download_full_toml_test_suites.sh

      - name: Run TOML tests
        run: VTEST_TOML_DO_YAML_CONVERSION=1 VTEST_TOML_DO_LARGE_FILES=1 ./v test vlib/toml
