name: wasm backend CI

on:
  push:
    paths:
      - 'cmd/tools/builders/**.v'
      - 'vlib/builtin/**.v'
      - 'vlib/v/ast/**.v'
      - 'vlib/v/scanner/**.v'
      - 'vlib/v/parser/**.v'
      - 'vlib/v/checker/**.v'
      - 'vlib/v/gen/c/**.v'
      - 'vlib/v/builder/**.v'
      - 'vlib/v/cflag/**.v'
      - 'vlib/v/live/**.v'
      - 'vlib/v/util/**.v'
      - 'vlib/v/markused/**.v'
      - 'vlib/v/preludes/**.v'
      - 'vlib/v/gen/wasm/**.v'
      - 'vlib/v/gen/wasm/tests/**.v'
  pull_request:
    paths:
      - 'cmd/tools/builders/**.v'
      - 'vlib/builtin/**.v'
      - 'vlib/v/ast/**.v'
      - 'vlib/v/scanner/**.v'
      - 'vlib/v/parser/**.v'
      - 'vlib/v/checker/**.v'
      - 'vlib/v/gen/c/**.v'
      - 'vlib/v/builder/**.v'
      - 'vlib/v/cflag/**.v'
      - 'vlib/v/live/**.v'
      - 'vlib/v/util/**.v'
      - 'vlib/v/markused/**.v'
      - 'vlib/v/preludes/**.v'
      - 'vlib/v/gen/wasm/**.v'
      - 'vlib/v/gen/wasm/tests/**.v'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name == 'master' && github.sha || github.ref_name }}
  cancel-in-progress: true

jobs:
  wasm-backend-ubuntu:
    runs-on: ubuntu-22.04
    timeout-minutes: 121
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: make -j4 && ./v symlink -githubci
      - name: Build examples
        run: VTEST_ONLY=wasm ./v build-examples
      - name: Install wasmer to execute WASM modules
        run: |
          curl https://get.wasmer.io -sSfL | sh
          sudo ln -s ~/.wasmer/bin/wasmer /usr/local/bin
      - name: Test the WASM backend
        run: ./v test vlib/v/gen/wasm/tests/

  wasm-backend-macos:
    runs-on: macOS-12
    timeout-minutes: 121
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: make -j4 && ./v symlink -githubci
      - name: Build examples
        run: VTEST_ONLY=wasm ./v build-examples
      - name: Install wasmer to execute WASM modules
        run: |
          curl https://get.wasmer.io -sSfL | sh
          sudo ln -s ~/.wasmer/bin/wasmer /usr/local/bin
      - name: Test the WASM backend
        run: ./v test vlib/v/gen/wasm/tests/

  wasm-backend-windows:
    runs-on: windows-2022
    timeout-minutes: 121
    steps:
      - uses: actions/checkout@v4
      - name: Build V
        run: ./make.bat -msvc
      - name: Symlink V
        run: ./v symlink -githubci
      - name: Build examples
        run: $env:VTEST_ONLY='wasm'; v build-examples
      - name: Test the WASM backend
        run: v -stats test vlib/v/gen/wasm/tests/
