name: wasm backend CI

on:
  push:
    paths:
      - '!**'
      - '!**.md'
      - 'cmd/tools/builders/**.v'
      - 'vlib/builtin/**.v'
      - 'vlib/v/ast/**.v'
      - 'vlib/v/scanner/**.v'
      - 'vlib/v/parser/**.v'
      - 'vlib/v/checker/**.v'
      - 'vlib/v/gen/c/**.v'
      - 'vlib/v/builder/**.v'
      - 'vlib/v/cflag/**.v'
      - 'vlib/v/live/**.v'
      - 'vlib/v/util/**.v'
      - 'vlib/v/markused/**.v'
      - 'vlib/v/preludes/**.v'
      - 'vlib/v/gen/wasm/**.v'
      - 'vlib/v/gen/wasm/tests/**.v'
  pull_request:
    paths:
      - '!**'
      - '!**.md'
      - 'cmd/tools/builders/**.v'
      - 'vlib/builtin/**.v'
      - 'vlib/v/ast/**.v'
      - 'vlib/v/scanner/**.v'
      - 'vlib/v/parser/**.v'
      - 'vlib/v/checker/**.v'
      - 'vlib/v/gen/c/**.v'
      - 'vlib/v/builder/**.v'
      - 'vlib/v/cflag/**.v'
      - 'vlib/v/live/**.v'
      - 'vlib/v/util/**.v'
      - 'vlib/v/markused/**.v'
      - 'vlib/v/preludes/**.v'
      - 'vlib/v/gen/wasm/**.v'
      - 'vlib/v/gen/wasm/tests/**.v'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  wasm-backend-ubuntu:
    runs-on: ubuntu-22.04
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    timeout-minutes: 121
    steps:
      - uses: actions/checkout@v4

      - name: Build V
        run: make && ./v symlink -githubci

      - name: Build examples
        run: VTEST_ONLY=wasm ./v build-examples

      - name: Install wasmer to execute WASM modules
        run: |
          curl https://get.wasmer.io -sSfL | sh
          sudo ln -s ~/.wasmer/bin/wasmer /usr/local/bin

      - name: Test the WASM backend
        run: ./v test vlib/v/gen/wasm/tests/

  wasm-backend-macos:
    runs-on: macOS-12
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    timeout-minutes: 121
    steps:
      - uses: actions/checkout@v4

      - name: Build V
        run: make && ./v symlink -githubci

      - name: Build examples
        run: VTEST_ONLY=wasm ./v build-examples

      - name: Install wasmer to execute WASM modules
        run: |
          curl https://get.wasmer.io -sSfL | sh
          sudo ln -s ~/.wasmer/bin/wasmer /usr/local/bin

      - name: Test the WASM backend
        run: ./v test vlib/v/gen/wasm/tests/
#  wasm-backend-windows:
#    runs-on: windows-2022
#    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
#    timeout-minutes: 121
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: Build V
#        run: .\make.bat -msvc
#      - name: Symlink V
#        run: .\v.exe symlink -githubci
#
#      - name: Build examples
#        run: $env:VTEST_ONLY='wasm'; v build-examples
#
#      - name: Test the WASM backend
#        run: v -stats test vlib/v/gen/wasm/tests/
