name: CI Windows (GCC)

on:
  workflow_call:

env:
  VFLAGS: -cc gcc
  VERBOSE_MAKE: 1
  CACHE_ID: windows-gcc-${{ github.sha }}

jobs:
  build:
    runs-on: windows-2019
    if: github.event_name != 'push' || github.event.ref == 'refs/heads/master' || github.event.repository.full_name != 'vlang/v'
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          gcc --version
          ./make.bat -gcc
      - name: Test new v.c
        run: |
          ./v -showcc -o v.c cmd/v
          gcc -Werror -municode -w v.c
      - name: Install dependencies
        run: |
          ./v setup-freetype
          ./.github\workflows\windows-install-sqlite.bat
      - name: V doctor
        run: ./v doctor
      - name: Cache
        uses: actions/cache/save@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}

  verify:
    needs: build
    runs-on: windows-2019
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}
          fail-on-cache-miss: true
      - name: Self compie
        run: ./v -o v2.exe cmd/v && .\v2.exe -o v3.exe cmd/v
      - name: Verify `v test` works
        run: |
          echo $VFLAGS
          ./v cmd/tools/test_if_v_test_system_works.v
          ./cmd/tools/test_if_v_test_system_works
      - name: Test pure V math module
        run: ./v -exclude @vlib/math/*.c.v test vlib/math/

  fmt:
    needs: build
    runs-on: windows-2019
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}
          fail-on-cache-miss: true
      - name: Test fmt
        run: ./v test-fmt
      - name: Test cleancode
        run: ./v test-cleancode

  # TODO: compare with linux and macos test other
  test-other:
    needs: verify
    runs-on: windows-2019
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}
          fail-on-cache-miss: true
      - name: Test V binaries
        run: ./v build-vbinaries
      - name: Build option_test.v with -autofree
        run: ./v -autofree vlib/v/tests/option_test.v

  test-self:
    needs: verify
    runs-on: windows-2019
    steps:
      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: ./
          key: ${{ env.CACHE_ID }}
          fail-on-cache-miss: true
      - name: Self tests
        run: .\v.exe test-self
      # - name: Test
      #   run: .\v.exe test-all

  examples-and-modules:
    needs: verify
    uses: ./.github/workflows/examples_and_modules_ci.yml
    with:
      os: windows-2019
      cc: gcc
      vflags: -cc gcc
